#!/usr/bin/env bash

TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-com.plexamp.Plexamp}"
FLAGS='--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer --enable-wayland-ime'
RED='\033[0;31m'
NC='\033[0m'

if [[ -e "$WAYLAND_DISPLAY" ]]
then
    WAYLAND_SOCKET=$WAYLAND_DISPLAY
else
    WAYLAND_SOCKET=$XDG_RUNTIME_DIR/${WAYLAND_DISPLAY:-"wayland-0"}
fi

if [[ -e "$WAYLAND_SOCKET" ]]
then
    echo -e "W[ae]yland detected, Yutani nowhere to be found... (${RED}--ozone-platform-hint=auto${NC})"
    FLAGS="$FLAGS --ozone-platform-hint=auto"

    if [[ $XDG_SESSION_TYPE == "wayland" && $XDG_CURRENT_DESKTOP == *"GNOME"* ]]
    then
        echo -e "Current desktop is GNOME... (${RED}--enable-features=WaylandWindowDecorations${NC})"
        FLAGS="$FLAGS --enable-features=WaylandWindowDecorations"
    fi

    if [[ $XDG_SESSION_TYPE =~ "[Ww]ayland" ]] && [ -c /dev/nvidia0 ]
    then
        echo -e "GPU is NVIDIA... ({$RED}--disable-gpu-sandbox${NC})"
        FLAGS="$FLAGS --disable-gpu-sandbox"
    fi
fi

echo -e "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/plexamp/plexamp $FLAGS "$@"
