#!/usr/bin/env bash

FEATURES="UseSkiaRenderer"
TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-com.plexamp.Plexamp}"
declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization)

if [[ "${XDG_SESSION_TYPE,,}" = "wayland" ]]; then
    echo "WAYLAND enabled, using the Wayland Electron backend"
    FEATURES="$FEATURES,UseOzonePlatform,WaylandWindowDecorations"
    FLAGS+=(-ozone-platform=wayland)

    # Just your normal NVIDIA things
    if [[ -c /dev/nvidia0 ]]; then
        echo "Using NVIDIA on Wayland, applying workaround"
        FLAGS+=(--disable-gpu-sandbox)
    fi

fi

FLAGS+=(--enable-features="${FEATURES}")
echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/plexamp/plexamp "${FLAGS[@]}" "$@"